# ---------------------------------------------------------------
# Hexo 核心配置文件
# 官方文档: https://hexo.io/zh-cn/docs/configuration
# 源码地址: https://github.com/hexojs/hexo/
# ---------------------------------------------------------------

# 网站信息 (Site)
# ---------------------------------------------------------------
# 网站主标题，会显示在浏览器标签页和主题的醒目位置。
title: Hexo
# 网站副标题，通常在主标题下方以小字显示。
subtitle: ''
# 网站描述，主要用于SEO，告诉搜索引擎你的网站是关于什么的。
description: ''
# 网站关键词，同样用于SEO，多个关键词用逗号隔开。
keywords:
# 网站作者，也就是你的名字或昵称。
author: John Doe
# 网站使用的语言。对于中文网站，请设置为 `zh-CN`。
language: zh-CN
# 网站时区。Hexo 默认使用您电脑的时区。
# 如果需要指定，可以设为 `Asia/Shanghai` 等。
# 时区列表: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# 网址 (URL)
# ---------------------------------------------------------------
# 设置你的网站访问地址。
# 如果你使用 GitHub Pages，格式为 'https://<你的用户名>.github.io/<你的仓库名>'
# 如果是绑定了自定义域名，就填写你的域名，例如 'https://www.example.com'。
url: http://example.com
# 文章的永久链接（URL）格式。
# :year, :month, :day, :title 等是可用的变量。
permalink: :year/:month/:day/:title/
# 永久链接中各变量的默认值。
permalink_defaults:
# URL美化，用于控制链接末尾的显示方式。
pretty_urls:
  # 是否移除永久链接末尾的 'index.html'。设为 false 则链接会以 /index.html 结尾。
  trailing_index: true
  # 是否移除永久链接末尾的 '.html'。设为 false 则链接会以 .html 结尾。
  trailing_html: true

# 目录 (Directory)
# ---------------------------------------------------------------
# 存放所有源文件的文件夹名称。
source_dir: source
# 最终生成的静态网站文件夹名称。
public_dir: public
# 标签页面的目录名称。
tag_dir: tags
# 归档页面的目录名称。
archive_dir: archives
# 分类页面的目录名称。
category_dir: categories
# 代码片段的目录名称（不常用）。
code_dir: downloads/code
# 国际化（i18n）语言文件的目录名称。
i18n_dir: :lang
# 跳过渲染的文件或文件夹。路径相对于 source 目录。
# 例如，你想让某个文件夹里的所有文件直接复制到 public 目录而不被处理，就可以写在这里。
# skip_render: 'path/to/something/**'
skip_render:

# 文章写作 (Writing)
# ---------------------------------------------------------------
# 使用 `hexo new` 命令创建新文章时，文件的默认名称格式。
new_post_name: :title.md
# 新建内容的默认布局（layout），通常是 'post'（文章）或 'page'（页面）。
default_layout: post
# 是否自动将文章标题转换为 "Title Case"（首字母大写）。
titlecase: false
# 外部链接处理。
external_link:
  # 是否在新标签页中打开所有外部链接。
  enable: true
  # 应用范围。'site' 表示全站，'post' 表示仅文章内。
  field: site
  # 在此处填写的域名将不会被视作外部链接。多个域名用逗号隔开。
  exclude: ''
# 将文件名转换为指定的大小写格式。0: 无变化, 1: 小写, 2: 大写。
filename_case: 0
# 是否渲染草稿文件夹 (`source/_drafts`) 中的文章。
render_drafts: false
# 是否为每篇文章创建一个同名的资源文件夹，用于存放图片等附件。
# 设置为 true 后，`hexo new "文章"` 会同时创建 `source/_posts/文章.md` 和 `source/_posts/文章/` 文件夹。
post_asset_folder: true
# 是否将链接转换为相对于根目录的路径。
relative_link: false
# 是否渲染发布日期在未来的文章。
future: true
# 语法高亮器的选择。可以是 `highlight.js` 或 `prism.js`。
# 注意：v7.0 版本后，需要手动安装对应插件，如 `npm install hexo-prism-plugin`。
syntax_highlighter: highlight.js
# `highlight.js` 的具体配置。
highlight:
  # 是否显示行号。
  line_number: true
  # 是否自动检测代码语言。
  auto_detect: false
  # 用什么字符替换 Tab 键，通常是几个空格。
  tab_replace: '  '
  # 是否用 `<table>` 包裹代码块以支持行号等功能。
  wrap: true
  # 是否启用 highlight.js 的自带高亮功能。
  # 通常由主题或插件接管，保持 false 即可。
  hljs: false
# `prism.js` 的具体配置。
prismjs:
  # 是否在生成时处理代码块。
  preprocess: true
  # 是否显示行号。
  line_number: true
  # 用什么字符替换 Tab 键。
  tab_replace: ''

# 首页设置 (Home page setting)
# ---------------------------------------------------------------
# 首页的生成器配置。
index_generator:
  # 首页的路径。默认是根目录。
  path: ''
  # 首页每页显示的文章数量。设为 0 表示不分页，显示所有文章。
  per_page: 10
  # 文章排序方式。`-date` 表示按日期降序（最新的在前）。
  order_by: -date

# 分类与标签 (Category & Tag)
# ---------------------------------------------------------------
# 未指定分类的文章的默认分类名。
default_category: uncategorized
# 分类别名映射。例如：`Gossip: 八卦`
category_map:
# 标签别名映射。例如：`Mac: Apple`
tag_map:

# 元数据元素 (Metadata elements)
# ---------------------------------------------------------------
# 是否在 <head> 中添加一个 meta 标签，注明是由 Hexo 生成的。
meta_generator: true

# 日期与时间格式 (Date / Time format)
# ---------------------------------------------------------------
# Hexo 使用 Moment.js 来处理日期。
# 格式化规则请参考：http://momentjs.com/docs/#/displaying/format/
# 日期显示格式。
date_format: YYYY-MM-DD
# 时间显示格式。
time_format: HH:mm:ss
# 文章的 `updated` 日期来源。
# 'mtime': 使用文件的最后修改时间 (推荐)。
# 'date': 使用 Front-matter 中的 `date` 值。
# 'empty': 不使用 `updated` 日期。
updated_option: 'mtime'

# 分页 (Pagination)
# ---------------------------------------------------------------
# 除首页外，其他归档页面（如分类、标签页）每页显示的文章数量。
# 设为 0 可禁用分页。
per_page: 10
# 分页页面的目录名称。例如，第二页的 URL 会是 /page/2/。
pagination_dir: page

# 包含/排除文件 (Include / Exclude file(s))
# ---------------------------------------------------------------
# 这些选项仅对 `source/` 文件夹生效。
# 强制包含某些文件或文件夹。
include:
# 排除某些文件或文件夹。
exclude:
# 忽略某些文件或文件夹（更强的排除）。
ignore:

# 扩展 (Extensions)
# ---------------------------------------------------------------
# 插件列表请参阅：https://hexo.io/plugins/
# 主题列表请参阅：https://hexo.io/themes/
# 当前使用的主题名称，必须与 `themes/` 目录下的文件夹名一致。
theme: fluid

# 部署 (Deployment)
# ---------------------------------------------------------------
# 部署配置。需要先安装对应的部署插件，如 `npm install hexo-deployer-git`。
# 官方文档: https://hexo.io/zh-cn/docs/one-command-deployment
deploy:
  # 部署类型。对于 GitHub Pages，通常是 'git'。
  type: git
  # 你的 GitHub 仓库地址。推荐使用 SSH 格式。
  repo: git@github.com:<你的用户名>/<你的仓库名>.git
  # 部署到的分支。对于 GitHub Pages，通常是 'gh-pages' 或 'main'。
  branch: gh-pages
  # 部署时的提交信息。
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"